name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  resource-group: rg-az400-eshopeonweb-NAME
  location: westeurope
  templateFile: .azure/bicep/webapp.bicep
  # subscriptionid: YOUR-SUBSCRIPTION-ID
  subscriptionid: YOUR-SUBSCRIPTION-ID
  azureserviceconnection: azure subs
  webappname: az400-webapp-NAME

jobs:

  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
        
    deploy:
   
